# Generated by Django 4.0.4 on 2023-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('added_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
